version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      - DEFAULT_REGION=us-east-2
      - SERVICES=apigateway,cloudformation,cloudwatch,iam,s3,secretsmanager
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - './.localstack:/tmp/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
    # tmpfs:
    #   - /tmp/localstack:exec,mode=600
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
          && awslocal cloudformation list-stacks
          && awslocal secretsmanager list-secrets
      interval: 5s
      timeout: 10s
      start_period: 10s
  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres/db_data:/var/lib/postgresql/data
      - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql
  # demo_localstack_app:
  #   build: './demo_localstack_app'
  #   image: "demo_localstack_app:latest"
  #   container_name: demo_localstack_app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - localstack
  #     - postgres
  #   environment:
  #     - PORT=3000
  #     - AWS_REGION=us-east-2
  #     - AWS_ACCESS_KEY_ID=0000
  #     - AWS_SECRET_ACCESS_KEY=0000
  #   command: sh -c "dockerize -wait tcp://postgres:5432 -wait http://localstack:4572 -timeout 60s -wait-retry-interval 10s npm start"